;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        end-of-visual-line
        helm-confirm-and-exit-minibuffer
        kill-visual-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-set-region
        org-cycle
        org-export-dispatch
        ))
